"""Initial

Revision ID: c54c4499be1c
Revises: 
Create Date: 2026-03-25 16:21:53.170663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54c4499be1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('CLIENT', 'CAREGIVER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clientId', sa.String(), nullable=False),
    sa.Column('caregiverId', sa.String(), nullable=True),
    sa.Column('serviceType', sa.Enum('CHILD', 'PET', 'ELDER', name='servicetype'), nullable=False),
    sa.Column('scheduledAt', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('tasks', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('checklist', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'COMPLETED', 'CANCELED', name='bookingstatus'), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caregiverId'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clientId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caregiver_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('experienceYears', sa.Integer(), nullable=True),
    sa.Column('hourlyRate', sa.Integer(), nullable=True),
    sa.Column('verificationStatus', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', name='verificationstatus'), nullable=True),
    sa.Column('categories', sa.String(), nullable=True),
    sa.Column('idCardUrl', sa.String(), nullable=True),
    sa.Column('diplomaUrl', sa.String(), nullable=True),
    sa.Column('verifiedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('client_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('care_recipients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clientProfileId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serviceType', sa.Enum('CHILD', 'PET', 'ELDER', name='servicetype'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('allergies', sa.String(), nullable=True),
    sa.Column('medications', sa.String(), nullable=True),
    sa.Column('emergencyContact', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clientProfileId'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ignored_bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bookingId', sa.String(), nullable=False),
    sa.Column('caregiverId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bookingId'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['caregiverId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('senderId', sa.String(), nullable=False),
    sa.Column('receiverId', sa.String(), nullable=False),
    sa.Column('bookingId', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bookingId'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiverId'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_updates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bookingId', sa.String(), nullable=False),
    sa.Column('caregiverId', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('checklist', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bookingId'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['caregiverId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bookingId', sa.String(), nullable=False),
    sa.Column('authorId', sa.String(), nullable=False),
    sa.Column('caregiverId', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bookingId'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['caregiverId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('quality_updates')
    op.drop_table('messages')
    op.drop_table('ignored_bookings')
    op.drop_table('care_recipients')
    op.drop_table('client_profiles')
    op.drop_table('caregiver_profiles')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
